package com.support.assistant.agent;

import com.support.assistant.model.dto.QueryPlan;
import com.support.assistant.model.dto.QueryRequest;
import com.support.assistant.model.dto.QueryResponse;
import com.support.assistant.model.entity.Document;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Holds the state of the agent workflow as it progresses through different stages.
 * This state is passed between agents and updated at each step.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AgentState {
    
    /**
     * The original query request from the user
     */
    private QueryRequest queryRequest;
    
    /**
     * The query plan generated by the planner agent
     */
    private QueryPlan queryPlan;
    
    /**
     * Documents retrieved by the retrieval agent
     */
    @Builder.Default
    private List<Document> retrievedDocuments = new ArrayList<>();
    
    /**
     * Compressed context after context compression
     */
    private String compressedContext;
    
    /**
     * The generated response from the synthesizer agent
     */
    private String generatedResponse;
    
    /**
     * Validation result from the validator agent
     */
    private ValidationResult validationResult;
    
    /**
     * Current workflow status
     */
    @Builder.Default
    private WorkflowStatus status = WorkflowStatus.INITIALIZED;
    
    /**
     * Additional metadata collected during workflow execution
     */
    @Builder.Default
    private Map<String, Object> metadata = new HashMap<>();
    
    /**
     * Timestamp when the workflow started
     */
    @Builder.Default
    private Instant startTime = Instant.now();
    
    /**
     * Timestamp when the workflow completed
     */
    private Instant endTime;
    
    /**
     * Error information if the workflow failed
     */
    private ErrorInfo errorInfo;
    
    /**
     * Number of retry attempts for the current stage
     */
    @Builder.Default
    private int retryCount = 0;
    
    /**
     * Add a metadata entry
     */
    public void addMetadata(String key, Object value) {
        this.metadata.put(key, value);
    }
    
    /**
     * Get a metadata entry
     */
    @SuppressWarnings("unchecked")
    public <T> T getMetadata(String key, Class<T> type) {
        return (T) this.metadata.get(key);
    }
    
    /**
     * Mark the workflow as complete
     */
    public void complete() {
        this.status = WorkflowStatus.COMPLETE;
        this.endTime = Instant.now();
    }
    
    /**
     * Mark the workflow as failed
     */
    public void fail(String errorMessage, Throwable cause) {
        this.status = WorkflowStatus.FAILED;
        this.endTime = Instant.now();
        this.errorInfo = new ErrorInfo(errorMessage, cause);
    }
    
    /**
     * Increment retry count
     */
    public void incrementRetry() {
        this.retryCount++;
    }
    
    /**
     * Reset retry count
     */
    public void resetRetry() {
        this.retryCount = 0;
    }
    
    /**
     * Error information
     */
    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    public static class ErrorInfo {
        private String message;
        private Throwable cause;
    }
}
